Add the ability to use custom audio button message
semsystems/chat-ui-react pull request #3
Opened 2021-08-23 12:16 UTC by Lmenkovaa

2021-08-25 09:51 UTC, KovalM requested changes
We need to add dist files to repo for getting this lib by including github. See example here: https://github.com/KovalM/chat-ui-react/tree/github-publication

2021-08-25 09:51 UTC, KovalM commented on package.json
> +    "chat-ui-react": "^0.2.14",
Why we need old version dependency?

2021-08-25 09:51 UTC, KovalM commented on src/mui/MuiMessage.tsx
> +  style= {{flex: '1 0 0%', display: 'flex',flexDirection: 'row', border: '0px', color: 'rgb(63, 81, 181)', margin: '0px 0px 5px 10px', height: '20px', width: '20px', boxShadow: '1px 1px 2px rgba(0,0,
Move styles to start of component

2021-08-25 09:51 UTC, KovalM commented on src/mui/MuiMessage.tsx
> +                  <AudioMessageButton {...audioButtonProps}/>
```suggestion
                  <AudioMessageButton onClick={playSoundContent} {...audioButtonProps}/>
```

2021-08-25 09:51 UTC, KovalM commented on src/mui/MuiMessage.tsx
> +                </div>
```suggestion
```

2021-08-25 09:51 UTC, KovalM commented on src/mui/MuiMessage.tsx
> +                  <AudioMessageButton {...audioButtonProps}/>
I don't test it, try please

2021-08-29 22:38 UTC, Lmenkovaa commented on src/mui/MuiMessage.tsx
> +                  <AudioMessageButton {...audioButtonProps}/>
It's doesn't work

2021-12-22 16:45 UTC, KovalM approved these changes

2021-12-22 16:45 UTC, merged